
package com.verisign._2006._08.vipservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "vipSoapInterfaceService", targetNamespace = "http://www.verisign.com/2006/08/vipservice", wsdlLocation = "file:/C:/alin/workspace/tmp/vip_prov.wsdl")
public class VipSoapInterfaceService
    extends Service
{

    private final static URL VIPSOAPINTERFACESERVICE_WSDL_LOCATION;
    private final static WebServiceException VIPSOAPINTERFACESERVICE_EXCEPTION;
    private final static QName VIPSOAPINTERFACESERVICE_QNAME = new QName("http://www.verisign.com/2006/08/vipservice", "vipSoapInterfaceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/alin/workspace/tmp/vip_prov.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIPSOAPINTERFACESERVICE_WSDL_LOCATION = url;
        VIPSOAPINTERFACESERVICE_EXCEPTION = e;
    }

    public VipSoapInterfaceService() {
        super(__getWsdlLocation(), VIPSOAPINTERFACESERVICE_QNAME);
    }

    public VipSoapInterfaceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VIPSOAPINTERFACESERVICE_QNAME, features);
    }

    public VipSoapInterfaceService(URL wsdlLocation) {
        super(wsdlLocation, VIPSOAPINTERFACESERVICE_QNAME);
    }

    public VipSoapInterfaceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VIPSOAPINTERFACESERVICE_QNAME, features);
    }

    public VipSoapInterfaceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VipSoapInterfaceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VipSoapInterface
     */
    @WebEndpoint(name = "vipServiceAPI")
    public VipSoapInterface getVipServiceAPI() {
        return super.getPort(new QName("http://www.verisign.com/2006/08/vipservice", "vipServiceAPI"), VipSoapInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VipSoapInterface
     */
    @WebEndpoint(name = "vipServiceAPI")
    public VipSoapInterface getVipServiceAPI(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.verisign.com/2006/08/vipservice", "vipServiceAPI"), VipSoapInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIPSOAPINTERFACESERVICE_EXCEPTION!= null) {
            throw VIPSOAPINTERFACESERVICE_EXCEPTION;
        }
        return VIPSOAPINTERFACESERVICE_WSDL_LOCATION;
    }

}
