
package com.verisign._2006._08.vipservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "vipSoapInterface", targetNamespace = "http://www.verisign.com/2006/08/vipservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VipSoapInterface {


    /**
     * 
     * @param getServerTime
     * @return
     *     returns com.verisign._2006._08.vipservice.GetServerTimeResponseType
     */
    @WebMethod(operationName = "GetServerTime")
    @WebResult(name = "GetServerTimeResponse", targetNamespace = "http://www.verisign.com/2006/08/vipservice", partName = "GetServerTimeResponse")
    public GetServerTimeResponseType getServerTime(
        @WebParam(name = "GetServerTime", targetNamespace = "http://www.verisign.com/2006/08/vipservice", partName = "GetServerTime")
        GetServerTimeType getServerTime);

    /**
     * 
     * @param getActivationCode
     * @return
     *     returns com.verisign._2006._08.vipservice.GetActivationCodeResponseType
     */
    @WebMethod(operationName = "GetActivationCode")
    @WebResult(name = "GetActivationCodeResponse", targetNamespace = "http://www.verisign.com/2006/08/vipservice", partName = "GetActivationCodeResponse")
    public GetActivationCodeResponseType getActivationCode(
        @WebParam(name = "GetActivationCode", targetNamespace = "http://www.verisign.com/2006/08/vipservice", partName = "GetActivationCode")
        GetActivationCodeType getActivationCode);

    /**
     * 
     * @param getSharedSecret
     * @return
     *     returns com.verisign._2006._08.vipservice.GetSharedSecretResponseType
     */
    @WebMethod(operationName = "GetSharedSecret")
    @WebResult(name = "GetSharedSecretResponse", targetNamespace = "http://www.verisign.com/2006/08/vipservice", partName = "GetSharedSecretResponse")
    public GetSharedSecretResponseType getSharedSecret(
        @WebParam(name = "GetSharedSecret", targetNamespace = "http://www.verisign.com/2006/08/vipservice", partName = "GetSharedSecret")
        GetSharedSecretType getSharedSecret);

    /**
     * 
     * @param getACStatus
     * @return
     *     returns com.verisign._2006._08.vipservice.GetACStatusResponseType
     */
    @WebMethod(operationName = "GetACStatus")
    @WebResult(name = "GetACStatusResponse", targetNamespace = "http://www.verisign.com/2006/08/vipservice", partName = "GetACStatusResponse")
    public GetACStatusResponseType getACStatus(
        @WebParam(name = "GetACStatus", targetNamespace = "http://www.verisign.com/2006/08/vipservice", partName = "GetACStatus")
        GetACStatusType getACStatus);

    /**
     * 
     * @param getOrderStatus
     * @return
     *     returns com.verisign._2006._08.vipservice.GetOrderStatusResponseType
     */
    @WebMethod(operationName = "GetOrderStatus")
    @WebResult(name = "GetOrderStatusResponse", targetNamespace = "http://www.verisign.com/2006/08/vipservice", partName = "GetOrderStatusResponse")
    public GetOrderStatusResponseType getOrderStatus(
        @WebParam(name = "GetOrderStatus", targetNamespace = "http://www.verisign.com/2006/08/vipservice", partName = "GetOrderStatus")
        GetOrderStatusType getOrderStatus);

}
